export const PROBE_CLIENT_TIMEOUT_MS = 20000;
export const PROBE_MODELS_TIMEOUT_MS = 8000;
export const PROBE_FALLBACK_MAX_CANDIDATES = 3;
export const PROBE_FALLBACK_REQUEST_TIMEOUT_MS = 1200;
export const PROBE_FALLBACK_MAX_ATTEMPTS_PER_CANDIDATE = 3;

export function getProbeWorstCaseTimeoutMs(): number {
  return (
    PROBE_MODELS_TIMEOUT_MS +
    PROBE_FALLBACK_MAX_CANDIDATES *
      PROBE_FALLBACK_REQUEST_TIMEOUT_MS *
      PROBE_FALLBACK_MAX_ATTEMPTS_PER_CANDIDATE
  );
}
